name: Tests

on:
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    concurrency: 
      group: pr-${{ github.head_ref }}
      cancel-in-progress: true
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    env:
      NODE_ENV: test
      TEST_DATABASE_URL: mongodb://localhost/mimas_test
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GOOGLE_OAUTH_CLIENT_ID_ANDROID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
      GOOGLE_OAUTH_CLIENT_ID_WEB: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID_WEB }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      CURRENT_API_VERSION: "0.1.0"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Clean install dependencies
        run: rm -rf node_modules && yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test
